version: '3'

services:

  postgres:
    image: "postgres:9.6.5"
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cutter_user
      - POSTGRES_PASSWORD=cutter_pass
      - POSTGRES_DATABASE=cutter_db

  rabbitmq:
    image: rabbitmq:3.6.12
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"