# Generated by Django 2.0.4 on 2018-05-04 13:17

from django.db import migrations, models
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(blank=True, max_length=60)),
                ('original_filename', models.CharField(blank=True, max_length=64)),
                ('upload', models.FileField(upload_to=files.models.audio_file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
