# Generated by Django 2.0.4 on 2018-05-04 20:21

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(blank=True, max_length=60)),
                ('original_filename', models.CharField(blank=True, max_length=64)),
                ('upload', models.FileField(upload_to=files.models.audio_file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileProcessingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='fileaudio',
            name='processing_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.FileProcessingState'),
        ),
    ]
