# Generated by Django 2.0.4 on 2018-04-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaudio',
            name='temp_file',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='files.TempFile'),
        ),
    ]
