# Generated by Django 2.0.4 on 2018-04-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180425_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaudio',
            name='original_filename',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
