# Generated by Django 2.0.4 on 2018-04-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_fileaudio_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaudio',
            name='original_filename',
            field=models.CharField(max_length=64),
        ),
    ]
